apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment # name of the deployment

spec:
  template: # pod defintion
    metadata:
      name: helloworld # name of the pod
      labels:
        app: helloworld
        tier: frontend
    spec:
      containers:
        - name: helloworld
          image: shuchitha/helloworld:latest
  replicas: 3
  selector: # Mandatory, Select the pods which needs to be in the replicaset
    matchLabels:
      app: helloworld
      tier: frontend
